
#include "game.h"



struct sprite spaceship = {
	.speed = 5,
	.w = 26,
	.h = 21,
	.a = {
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,GR,GR,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,GR,GR,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,GR,GR,GR,GR,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,GR,GR,GR,GR,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,YE,BL,BL,BL,BL,BL,GR,GR,GR,GR,GR,GR,BL,BL,BL,BL,BL,YE,BL,BL,BL,BL,
		BL,BL,BL,GR,GR,BL,BL,BL,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,BL,BL,BL,GR,GR,BL,BL,BL,
		BL,BL,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,BL,BL,
		BL,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,BL,
		BL,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,BL,
		BL,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,BL,
		BL,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,BL,
		BL,GR,GR,GR,GR,GR,GR,GR,WH,WH,WH,GR,GR,GR,GR,WH,WH,WH,GR,GR,GR,GR,GR,GR,GR,BL,
		BL,GR,GR,GR,GR,GR,GR,WH,RE,RE,RE,WH,GR,GR,WH,RE,RE,RE,WH,GR,GR,GR,GR,GR,GR,BL,
		BL,GR,GR,GR,GR,GR,WH,RE,RE,RE,RE,RE,GR,GR,RE,RE,RE,RE,RE,WH,GR,GR,GR,GR,GR,BL,
		BL,BL,BL,GR,GR,WH,RE,RE,RE,RE,RE,RE,WH,WH,RE,RE,RE,RE,RE,RE,WH,GR,GR,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,RE,RE,RE,RE,RE,BL,BL,RE,RE,RE,RE,RE,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,RE,RE,RE,BL,BL,BL,BL,RE,RE,RE,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,RE,RE,RE,BL,BL,BL,BL,RE,RE,RE,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,RE,BL,BL,BL,BL,BL,BL,RE,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
	}
};


struct sprite enemyBorg = {
	.x = 10,
	.y = 10,
	.dir = 0,
	.speed = 1,
	.w = 22,
	.h = 22,
	.a = {
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
		BL,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,BL,
		BL,WH,WH,GY,WH,WH,GY,WH,GY,WH,GY,WH,WH,WH,GY,WH,WH,WH,GY,WH,WH,BL,
		BL,WH,GY,WH,WH,WH,GY,WH,GY,WH,GY,WH,WH,WH,GY,WH,WH,WH,GY,WH,WH,BL,
		BL,WH,GY,WH,WH,GY,WH,WH,GY,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,BL,
		BL,WH,GY,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,WH,WH,BL,
		BL,WH,WH,WH,GY,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,WH,WH,WH,BL,
		BL,WH,WH,WH,GY,WH,WH,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,GY,WH,GY,WH,BL,
		BL,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,GY,WH,GY,WH,GY,WH,GY,WH,GY,WH,BL,
		BL,WH,GY,WH,WH,WH,GY,WH,WH,WH,WH,WH,WH,GY,WH,GY,WH,GY,WH,GY,WH,BL,
		BL,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,WH,GY,WH,GY,WH,BL,
		BL,WH,WH,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,WH,GY,WH,WH,GY,WH,BL,
		BL,WH,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,WH,GY,WH,WH,GY,WH,WH,BL,
		BL,WH,GY,WH,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,BL,
		BL,WH,GY,WH,GY,WH,GY,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,GY,WH,WH,WH,BL,
		BL,WH,GY,WH,GY,WH,GY,WH,GY,WH,GY,WH,WH,WH,WH,GY,WH,WH,WH,GY,WH,BL,
		BL,WH,GY,WH,GY,WH,GY,WH,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,GY,WH,WH,BL,
		BL,WH,WH,WH,GY,WH,GY,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,GY,WH,WH,WH,BL,
		BL,WH,WH,GY,WH,WH,GY,WH,GY,WH,WH,WH,GY,WH,WH,GY,WH,GY,WH,GY,WH,BL,
		BL,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,WH,GY,WH,GY,WH,BL,
		BL,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,WH,BL,
		BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
	}
};





